// authProvider Status Codes
const USER_NAME_IS_NOT_PROVIDED = 400;
const NAME_OF_USER_IS_NOT_PROVIDED = 400;
const USER_PRIMARY_EMAIL_IN_NOT_PROVIDED = 400;
const USER_PASSWORD_IS_NOT_PROVIDED = 400;
const USER_ALREADY_EXIST = 409;
const AUTHENTICATION_TOKEN_GENERATION_ERROR = 400;
const AUTHENTICATION_TOKEN_IS_GENERATED = 200;
const USER_NOT_EXIST = 404;
const USER_INVALID_CREDENTIAL = 401;
const USER_REGISTERED_SUCCESSFULLY = 200;
const USER_CREDENTIAL_VERIFIED = 200;
const USER_VERIFIED_WITH_AUTHENTICATION_TOKEN = 200;
const USER_UPDATED_SUCCESSFULLY = 200;

// userProvider Status Codes
const FETCH_ALL_USERS_IS_SUCCESSFUL = 200;
const USER_FOUND_SUCCESSFULLY = 200;

// taskProvider Status Codes
const TASK_FETCHED_SUCCESSFULLY = 200;
const TASK_CREATOR_IS_NOT_PROVIDED = 400;
const TASK_TITLE_IS_NOT_PROVIDED = 400;
const TASK_BASICDETAILS_IS_NOT_PROVIDED = 400;
const TASK_TIMINGANDSCHEDULE_IS_NOT_PROVIDED = 400;
const TASK_CREATED_SUCCESSFULLY = 200;
const TASK_UPDATED_SUCCESSFULLY = 200;
const TASK_NOT_FOUND = 404;
const TASK_DELETED_SUCCESSFULLY = 200;

// teamProvider Status Codes
const TEAM_NOT_FOUND = 404;
const TEAM_FOUND_SUCCESSFULLY = 200;
const TEAMNAME_IS_NOT_PROVIDED = 400;
const TEAM_BASICDETAILS_IS_NOT_PROVIDED = 400;
const TEAM_MEMBERS_IS_NOT_PROVIDED = 400;
const TEAM_LEADER_IS_NOT_PROVIDED = 400;
const TEAM_MEMBER_NOT_FOUND_IN_USER_DATABASE = 404;
const TEAM_CREATED_SUCCESSFULLY = 200;
const TEAM_UPDATED_SUCCESSFULLY = 200;
const TEAM_DELETED_SUCCESSFULLY = 200;

// supervisorProvider Status Codes
const SUPERVISOR_NOT_FOUND = 404;
const SUPERVISOR_FOUND_SUCCESSFULLY = 200;
const SUPERVISOR_NAME_IS_NOT_PROVIDED = 400;
const SUPERVISOR_PRIMARYEMAIL_IS_NOT_PROVIDED = 400;
const SUPERVISOR_ADDED_SUCCESSFULLY = 200;
const SUPERVISOR_UPDATED_SUCCESSFULLY = 200;
const SUPERVISOR_REMOVED_SUCCESSFULLY = 200;
const FETCH_ALL_SUPERVISOR_IS_SUCCESSFUL = 200;

// authMiddleware Status Codes
const TOKEN_NOT_GENERATED = 400;
const TOKEN_EXPIRES = 400;

// mongoDB server error Status Codes
const MONGODB_SERVER_ERROR_FIND = 500;
const MONGODB_SERVER_ERROR_FINDBYID = 500;
const MONGODB_SERVER_ERROR_FINDBYIDANDDELETE = 500;
const MONGODB_SERVER_ERROR_FINDBYIDANDUPDATE = 500;
const MONGODB_SERVER_ERROR_FINDONE = 500;
const MONGODB_SERVER_ERROR_FINDONEANDDELETE = 500;
const MONGODB_SERVER_ERROR_FINDONEANDREPLACE = 500;
const MONGODB_SERVER_ERROR_FINDONEANDUPDATE = 500;
const MONGODB_SERVER_ERROR_SAVE = 500;

// Internal server error Status Codes
const INTERNAL_SERVER_ERROR_BCRYPT_COMPARE = 500;