// authProvider Status Codes
const USER_NAME_IS_NOT_PROVIDED = 600;
const NAME_OF_USER_IS_NOT_PROVIDED = 601;
const USER_PRIMARY_EMAIL_IN_NOT_PROVIDED = 602;
const USER_PASSWORD_IS_NOT_PROVIDED = 603;
const USER_ALREADY_EXIST = 604;
const AUTHENTICATION_TOKEN_GENERATION_ERROR = 605;
const AUTHENTICATION_TOKEN_IS_GENERATED = 606;
const USER_NOT_EXIST = 607;
const USER_INVALID_CREDENTIAL = 608;
const USER_REGISTERED_SUCCESSFULLY = 609;
const USER_CREDENTIAL_VERIFIED = 610;
const USER_VERIFIED_WITH_AUTHENTICATION_TOKEN = 611;
const USER_UPDATED_SUCCESSFULLY = 613;

// userProvider Status Codes
const FETCH_ALL_USERS_IS_SUCCESSFUL = 620;
const USER_FOUND_SUCCESSFULLY = 621;

// taskProvider Status Codes
const TASK_FETCHED_SUCCESSFULLY = 630;
const TASK_CREATOR_IS_NOT_PROVIDED = 631;
const TASK_TITLE_IS_NOT_PROVIDED = 632;
const TASK_BASICDETAILS_IS_NOT_PROVIDED = 633;
const TASK_TIMINGANDSCHEDULE_IS_NOT_PROVIDED = 634;
const TASK_CREATED_SUCCESSFULLY = 635;
const TASK_UPDATED_SUCCESSFULLY = 636;
const TASK_NOT_FOUND = 637;
const TASK_DELETED_SUCCESSFULLY = 638;

// teamProvider Status Codes
const TEAM_NOT_FOUND = 640;
const TEAM_FOUND_SUCCESSFULLY = 641;
const TEAMNAME_IS_NOT_PROVIDED = 642;
const TEAM_BASICDETAILS_IS_NOT_PROVIDED = 643;
const TEAM_MEMBERS_IS_NOT_PROVIDED = 644;
const TEAM_LEADER_IS_NOT_PROVIDED = 645;
const TEAM_MEMBER_NOT_FOUND_IN_USER_DATABASE = 646;
const TEAM_CREATED_SUCCESSFULLY = 647;
const TEAM_UPDATED_SUCCESSFULLY = 648;
const TEAM_DELETED_SUCCESSFULLY = 649;

// supervisorProvider Status Codes
const SUPERVISOR_NOT_FOUND = 660;
const SUPERVISOR_FOUND_SUCCESSFULLY = 661;
const SUPERVISOR_NAME_IS_NOT_PROVIDED = 662;
const SUPERVISOR_PRIMARYEMAIL_IS_NOT_PROVIDED = 663;
const SUPERVISOR_ADDED_SUCCESSFULLY = 664;
const SUPERVISOR_UPDATED_SUCCESSFULLY = 665;
const SUPERVISOR_REMOVED_SUCCESSFULLY = 666;
const FETCH_ALL_SUPERVISOR_IS_SUCCESSFUL = 667;

// authMiddleware Status Codes
const TOKEN_NOT_GENERATED = 700;
const TOKEN_EXPIRES = 701;

// mongoDB server error Status Codes
const MONGODB_SERVER_ERROR_FIND = 800;
const MONGODB_SERVER_ERROR_FINDBYID = 801;
const MONGODB_SERVER_ERROR_FINDBYIDANDDELETE = 802;
const MONGODB_SERVER_ERROR_FINDBYIDANDUPDATE = 803;
const MONGODB_SERVER_ERROR_FINDONE = 804;
const MONGODB_SERVER_ERROR_FINDONEANDDELETE = 805;
const MONGODB_SERVER_ERROR_FINDONEANDREPLACE = 806;
const MONGODB_SERVER_ERROR_FINDONEANDUPDATE = 807;
const MONGODB_SERVER_ERROR_SAVE = 808;

// Internal server error Status Codes
const INTERNAL_SERVER_ERROR_BCRYPT_COMPARE = 900;